# Title ex) Release v1.0.6 – 공통 응답코드 및 예외 핸들러 추가


# 📦 Release {{TAG_NAME}}

> **Release date:** {{YYYY-MM-DD}}  
> **Previous version:** {{PREVIOUS_TAG}}

---

## 📝 Overview
짧게 “무슨 기능이 추가/변경/수정되었는지” 한두 문장으로 요약합니다.

---

## ✨ New Features
- **{{모듈/컴포넌트 이름}}**:  
  - 설명1  
  - 설명2  
- **{{다른 기능}}**:  
  - 설명

---

## 🐛 Bug Fixes
- **{{이슈 번호 or 증상}}**:  
  - 수정 내용  
- **{{다른 버그}}**:  
  - 수정 내용

---

## 📈 Improvements
- **성능**: 로딩 속도 개선  
- **코드 리팩터링**: 공통 유틸 메서드 정리  
- **문서**: README 예제 추가

---

## ⚠️ Breaking Changes
> (호환성 깨지는 변경이 있을 때만)  
- **{{이전 API}}** → **{{새 API}}** 로 변경됨  
- X 옵션 기본값이 `false` → `true` 로 바뀜

---

## 🔧 Migration
1. `build.gradle` 에서 `version` 을 `{{NEW_VERSION}}` 으로 변경  
2. `artifactId`/`groupId` 는 그대로 유지  
3. (필요 시) 추가로 바뀐 설정이나 환경 변수 안내

---

## 📌 How to Upgrade
```groovy
dependencies {
    implementation "com.github.ryulkim:LibCC:{{TAG_NAME}}"
}
