oauth2:
  client-id: id
  client-secret: secret
  redirect-uri: http://localhost:8080/auth
  token-uri: https://oauth2.googleapis.com/token
  user-info-uri: https://www.googleapis.com/userinfo/v2/me
jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expiration-time: 1800000  # 30분 (밀리초 단위)
  refresh-token-expiration-time: 604800000  # 7일 (밀리초 단위)
  refresh-token-expiration-time-cookie: 604800 # 7일 (초 단위)
app:
  oauth2:
    authorizedRedirectUris: http://localhost:5173/oauth/redirect